In [2]:
# Creation on one dimensional array
import numpy as np
list=[1,2,3,4]
# list=[1,2.2,3,4] saare ko float me kar dega
# list=[1,2,'h',4]  saare ko string me kar dega
array1=np.array(list)
print(array1)
print(type(array1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
# Two dimensional array creation
import numpy as np
list=[[1,2,3],[4,5,6],[7,8,9]]
array1=np.array(list)
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Array Creation using range
import numpy as np
array1=np.arange(1,8)
print(array1)

[1 2 3 4 5 6 7]


In [6]:
# 2D array creation using range
import numpy as np
array1=np.arange(11,17).reshape(2,3)
print(array1)


[[11 12 13]
 [14 15 16]]


In [5]:
# Array Creation whose all elements are zeros..... similarly you can create for 1 you can write ones in terms of zeros
import numpy as np
array1=np.zeros(4)
print(array1)

[0. 0. 0. 0.]


In [8]:
# 2D Array Creation whose all elements are zeros
import numpy as np
array1=np.zeros((3,2))
print(array1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
# Attributes of numpy arrays
# 1)ndim
# import numpy as np
# list1=[1,2,3,4]
# array1=np.array(list1)
# print(array1.ndim)

# for 2D array
import numpy as np
list=[[1,2,3],[4,5,6],[7,8,9]]
array1=np.array(list)
print(array1.ndim)

2


In [16]:
# 2) Shape(rows,column)
# import numpy as np
# list=[1,2,3,4]
# array1=np.array(list)
# print(array1.shape)

# for 2D array
import numpy as np
list=[[1,2,3,4],[5,6,7,8]]
array1=np.array(list)
print(array1.shape)

(2, 4)


In [19]:
# 3) Size(total elements)
# import numpy as np
# list=[1,2,3,4]
# array1=np.array(list)
# print(array1.size)

# for 2D array
import numpy as np
list=[[1,2,3,4],[5,6,7,8]]
array1=np.array(list)
print(array1.size)


8


In [22]:
# 4) dtype
# import numpy as np
# list=[1,2,3,4]
# array1=np.array(list)
# print(array1.dtype)

# for 2D array
import numpy as np
list=[[1,2,3,4],[5,6,7,8]]
array1=np.array(list)
print(array1.dtype)

int32


In [23]:
# 5) itemsize
import numpy as np
list=[1,2,3,4]
array1=np.array(list)
print(array1.itemsize)

# for 2D array
# import numpy as np
# list=[[1,2,3,4],[5,6,7,8]]
# array1=np.array(list)
# print(array1.itemsize)

4


In [24]:
# Indexing in numpy Arrays

# import numpy as np
# list=[1,2,3,4]
# array1=np.array(list)
# print(array1[0]) // 1
# print(array1[-1]) // 4

# for 2D array
import numpy as np
list=[[1,2,3],[4,5,6],[7,8,9]]
array1=np.array(list)
print(array1[1,2)
print(array1[0,:)
print(array1[:,1)

2
3


In [25]:
# Slicing
# import numpy as np
# list=[10,20,30,40,50,60]
# array1=np.array(list)
# print(array1[1:3])
# print(array1[2:6:2])
# print(array1[-1:-3:-1])
# print(array1[::-1])

# 2D array slicing
import numpy as np
list=[[15,16,17],[25,26,27],[35,36,37],[45,46,47]]
array1=np.array(list)
print(array1[1,])
print(array1[:,3])
print(array1[1:3,1:3])
print(array1[1:3,])
print(array1[:,1:3])
print(array1[1:3,1])
print(array1[1:3,:1])




[20 30]


In [27]:
# Arithmetic Operations on numpy arrays
# 1) Addition(+) 2) Subtraction(-) 3) Multiplication(simple multiplication(*) karega)
# 4) metrics multiplication(@) 5) Division(/) 6) floor division(//) 7)Exponentiations(**)
# 8) Modulo(% Remainder deta hai) 9) Transpose

import numpy as np
x=np.array([[1,2,3],[4,3,2]])
y=np.array([[4,6,7],[2,3,4]])
# z=x+y
print(x.transpose())

[[1 4]
 [2 3]
 [3 2]]


In [ ]:
# Sorting in numpy arrays
1) np.sort() // it will returns a sorted copy of an array
2) np.argsort() // will return the indices that would sort an array


In [28]:
import numpy as np
x=np.array([4,5,3,2,7])
y=np.sort(x) #// ascending oredr me sort karega
# y=np.sort(x)[::-1] // decending order me sort hoga
print(y)

[2 3 4 5 7]


In [29]:
import numpy as np
x=np.array([4,5,3,2,7])
y=np.argsort(x) # sorted array ka index return karega
print(y)

[3 2 0 1 4]


In [ ]:
 Staticals Operations on numpy arrays
1) Max() 2) Min() 3)Sum() 4) Mean()
5) median() 6) prod() 7) var() 8) std()

In [30]:
import numpy as np
x=np.array([4,5,3,2,7])
y=np.max(x) 
print(y)
# similarly you can create for all

7
